#!/usr/bin/env python3
"""第六章 — 清道夫之战（50格）"""
Q="Young Chinese man 25yo, thin black-frame glasses, short black hair with bangs, beige casual blazer, dark blue V-neck shirt, old black backpack, tired hollow eyes, pale skin"
S="Manhua ink wash, black white, dramatic lighting, G-pen linework, grayscale, realistic."
PANELS=[
("P50_扉页",f"Split: {Q} pinned against alley wall, dark blade inches from throat, blue light beam piercing from darkness. title text. {S}","abstract"),
("P01_恍惚",f"Medium shot {Q} at office desk, hollow eyes, going through motions, body present mind elsewhere, three days of haunting paranoia. {S}","character"),
("P02_被注视",f"{Q} at desk, invisible pressure of being watched, {Q} turning head but seeing empty corner. {S}","character"),
("P03_张明远盯",f"Corner desk, Zhang Mingyuan sitting motionless staring directly at {Q} back, unsettling stillness, only {Q} can see him. {S}","supernatural"),
("P04_失眠",f"{Q} sitting up in bed at midnight, all lights on, dark circles under eyes, checking every corner, nothing there but feeling watched. {S}","character"),
("P05_第四天深夜",f"Wide shot {Q} walking home late at night, passing through old neighborhood, entering dark alley without streetlights, familiar route. {S}","scene"),
("P06_路灯全灭",f"Alley streetlights all extinguishing simultaneously, {Q} frozen mid-step, complete darkness descending, dramatic blackout. {S}","scene"),
("P07_硫磺味",f"Close-up {Q} nostrils flaring, familiar acrid sulfur stench flooding alley, suffocating thickness, nightmare returning. {S}","character"),
("P08_身影走来",f"Dark figure emerging from alley depths, footsteps echoing in dead silence, {Q} backed against wall, heart pounding. {S}","scene"),
("P09_皮肤融化",f"Close-up Zhang Mingyuan face, skin melting like candle wax dripping down, revealing black涌动符文 beneath, horror unmasked. {S}","supernatural"),
("P10_虫子般的符文",f"Extreme close-up: black符文 writhing under skin like living insects, eyes now complete black voids with something burning inside. {S}","supernatural"),
("P11_金属摩擦声",f"Zhang Mingyuan speaking, mouth distorting, voice尖锐 with overlapping echoes, metal scraping glass quality, addressing {Q} directly. {S}","supernatural"),
("P12_意外之喜",f"Medium shot creature leaning close to {Q}, dead废物 left complete visual circuit, unexpected prize for cleaner to harvest. {S}","supernatural"),
("P13_退无可退",f"{Q} back pressed against alley wall, nowhere to run, trapped prey facing predator, fear but also something else rising. {S}","character"),
("P14_你是谁",f"Close-up {Q} demanding identity, voice shaking but standing ground, what are you. {S}","character"),
("P15_清道夫",f"Creature tilting head, melted skin dripping on ground with sizzling sound like acid, identifying itself as Cleaner,遗物 disposal unit. {S}","supernatural"),
("P16_那个女生",f"{Q} gasping question about warning girl, who is she, desperate for answers before death. {S}","character"),
("P17_叛徒",f"Creature laughing harshly, she is also Cleaner,只是叛徒, she wants to harvest you after fattening, her protection is lie. {S}","supernatural"),
("P18_黑暗利刃",f"Creature hand transforming into blade of pure condensed darkness, edge glowing with ominous light, killing strike preparing. {S}","supernatural"),
("P19_你是我的了",f"Dark blade raised high, creature lunging, predator claiming prey, eat you evolve, do not struggle it is quick. {S}","supernatural"),
("P20_时间变慢",f"Abstract: blade in slow motion approaching {Q} throat, time stretching, {Q} perception expanding, moment of extreme crisis. {S}","abstract"),
("P21_反击",f"Close-up {Q} eyes, internal calculation:反击 or die, stuck in夹缝 better than becoming food, survival override. {S}","character"),
("P22_看着我",f"{Q} eyes wide open staring at creature, familiar urge exploding from deep consciousness like imprisoned beast breaking free, pulling trigger. {S}","character"),
("P23_世界灰白",f"Wide shot: alley transforming to grayscale monochrome, only creature glowing with blinding red targeting light brighter than ever before. {S}","supernatural"),
("P24_寒意剥离",f"Abstract: cold force separating from {Q} body, but this time stretching like rubber band pulled too far, trembling vibrating warning. {S}","abstract"),
("P25_爆炸",f"Energy exploding mid-air between {Q} and creature,冲击波 throwing {Q} to ground, ears ringing, warm liquid from nose. {S}","abstract"),
("P26_肩膀炸开",f"Creature staggering, left shoulder blasted open with hole, black liquid pouring out, injured but not dead, screaming rage. {S}","supernatural"),
("P27_凡人",f"Creature screaming about废物 power, {Q} is mere mortal can not wield even fraction, now half destroyed but still enough to kill. {S}","supernatural"),
("P28_利刃再举起",f"Creature raising blade again over prone {Q} on ground, killing blow imminent, {Q} no strength to move, realization: girl was right. {S}","character"),
("P29_蓝光",f"Brilliant blue light beam piercing through creature chest from alley darkness, cold inorganic otherworldly light like giant needle, precise surgical strike. {S}","supernatural"),
("P30_钉在地上",f"Creature pinned to ground by blue beam, screaming扭曲 struggling, body beginning to disintegrate like burning newspaper from edges. {S}","supernatural"),
("P31_灰烬",f"Creature body crumbling to black ash floating in air, sulfur smell fading disappearing completely, alley returning to darkness and silence. {S}","scene"),
("P32_还活着",f"{Q} lying on ground gasping, head ringing, nose blood covering face, but alive, somehow still alive, staring at sky. {S}","character"),
("P33_脚步声",f"Light footsteps approaching from alley depths, not heavy monster steps, ordinary轻盈 human steps, someone walking toward {Q}. {S}","scene"),
("P34_少女",f"Figure standing over {Q}, looking down, eyes adjusting to dark: high school girl in uniform, ponytail, backpack, looks like any ordinary student. {S}","character"),
("P35_夸张的枪",f"Close-up: girl holding oversized gun with metallic光泽, definitely not normal student equipment, casually resting on shoulder. {S}","scene"),
("P36_蹲下",f"Girl squatting down tilting head examining {Q}, casual evaluating posture,棒棒糖 in other hand. {S}","character"),
("P37_啧",f"Close-up girl face, familiar tired沙哑 voice, the same voice from brain earlier, disappointment mixed with relief. {S}","character"),
("P38_差点就炸了",f"Girl speaking casually: told you not use ability, almost exploded, gun on shoulder,棒棒糖 in mouth, absurd contrast to situation. {S}","character"),
("P39_工具人二号",f"Girl calling {Q} Tool Number Two,平静生活结束了, asking if he can stand, offering to carry him but prefer self-walk because uniform freshly washed. {S}","character"),
("P40_夜空",f"{Q} lying on cold alley ground staring at small patch of night sky, city lights turning sky orange-red, no stars visible. {S}","character"),
("P41_回忆蒙太奇",f"Abstract montage: unemployed青年 on subway, bridge cave glowing runes, metallic voice, faces of 230 killed, smiling intern, melting monster, blue light. {S}","abstract"),
("P42_先吃顿饭",f"Close-up {Q} face, voice hoarse exhausted distant: can I eat first, have not had dinner. {S}","character"),
("P43_笑了",f"Girl face breaking into unexpected smile at absurd request,棒棒糖 nearly falling, genuine amusement breaking through tired exterior. {S}","character"),
("P44_伸出手",f"Girl extending hand toward {Q}, offering help up,烧烤摊 open until 3am,边吃边说, new alliance forming in dark alley. {S}","character"),
("P45_终幕",f"{Q} grabbing offered hand being pulled up, both figures walking into alley darkness together, toward烧烤摊 and unknown future. {S}","abstract"),
]
