#!/usr/bin/env python3
"""ch01 K2.7分镜 v3.1 — prompt显式带景别强指令"""

Q = '25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤'
S = 'East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.'

PANELS = [
    ('S1P1', f"【全景远景，人物占画面1/3，环境为主】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。东亚黑白漫画风格，拥挤地铁车厢内，速度线表现晃动，黑白色调中人群挤压。祁思远瘦削无神，穿旧衬衫，胸前紧夹背包，一手抓吊环，眼神空洞望向窗外，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'scene'),
    ('S1P2', f"【极端特写镜头，只画局部细节填满画面，不出现全身】特写背包拉链半开，露出三年前旧笔记本电脑一角，电源线缠绕，一只手指关节发白紧攥肩带。网点表现磨损与廉价感，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'prop'),
    ('S1P3', f"【中景，画腰部以上，人物占画面主体】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。CBD写字楼大堂，大理石与玻璃幕墙，西装革履的人潮来来往往。祁思远独自坐在休息区沙发低头刷手机，两名保安在远处交谈，没人看他，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'character'),
    ('S1P4', f"【中景，画腰部以上，人物占画面主体】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。街心公园长椅，祁思远侧身坐着，低头咬饭团。背景是高楼剪影与行道树， lonely atmosphere。两个饭团包装纸摊在旁边长椅上，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'character'),
    ('S1P5', f"【近景，画胸部以上半身，不出现全身】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。图书馆角落，老旧笔记本屏幕显示招聘网站列表，清一色已读不回。祁思远手指停在触摸板上，屏幕反光映出他疲惫的脸，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'character'),
    ('S1P6', f"【极端特写镜头，只画局部细节填满画面，不出现全身】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。祁思远脸部特写，眼神涣散，嘴角微微下拉，网点阴影覆盖眼下。手机画面虚化成无数未回复通知，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'character'),
    ('S2P1', f"【全景远景，人物占画面1/3，环境为主】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。待拆迁老街区远景，夕阳锈红色笼罩断壁残垣，裸露钢筋如枯骨。祁思远瘦削背影独自走在碎砖瓦砾之间，拉长的影子歪斜，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'scene'),
    ('S2P2', f"【中景，画腰部以上，人物占画面主体】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。两堵危墙夹峙的入口，生锈铁门半开，门后是荒废公园的黑暗深处。祁思远站在门前，身影被夕阳从背后照亮，面部隐于阴影，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'scene'),
    ('S2P3', f"【全景远景，人物占画面1/3，环境为主】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。荒废公园内部，杂草从石板缝隙疯长，歪斜的废弃游乐设施，塑料滑道积满黑色雨水。祁思远沿小径走向画面深处，速度线表现不稳定感，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'scene'),
    ('S2P4', f"【中景，画腰部以上，人物占画面主体】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。一座石桥横跨干涸河床，桥洞阴影浓重，像一张张开的嘴。夕阳锈红染在桥身，祁思远停在桥头，风衣被微风掀起一角，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'scene'),
    ('S2P5', f"【中景，画腰部以上，人物占画面主体】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。一个穿暗色风衣的女人背影，正走进桥洞的阴影，即将消失。祁思远在后方远处，眼睛微微睁大，身体前倾，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'character'),
    ('S3P1', f"【中景，画腰部以上，人物占画面主体】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。桥洞内部极暗，前后洞口透进微弱夕光。祁思远侧身站在中央，眯眼环顾，空气用漂浮尘埃与细密速度线表现凝滞。黑白色调中用密集网点表现暗部，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'atmosphere'),
    ('S3P2', f"【近景，画胸部以上半身，不出现全身】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。祁思远的手扶在桥壁上，墙面覆盖密密麻麻的发光刻痕，如血管与根系交错。黑白漫画中用白色线条与网点表现磷光搏动，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'effect'),
    ('S3P3', f"【极端特写镜头，只画局部细节填满画面，不出现全身】刻痕超微距，一部分像集成电路线路，一部分像古老符咒，线条扭曲痉挛，明暗如心跳搏动，周围散发微微热量波纹，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'effect'),
    ('S3P4', f"【中景，画腰部以上，人物占画面主体】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。祁思远背靠桥壁，脸色惨白，冷汗浸透衬衫领口，双腿僵直，嘴巴微张却喊不出声。身体周围刻痕发光逼近，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'character'),
    ('S3P5', f"【近景，画胸部以上半身，不出现全身】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。祁思远惊恐的脸部特写，眼睛瞪大，瞳孔收缩，网点阴影加重，嘴唇颤抖。画面用白色声波线从四周向中心收缩，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'character'),
    ('S4P1', f"【中景，画腰部以上，人物占画面主体】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。桥洞内壁刻痕光芒暴涨，中央阴影翻涌如巨大虚影，没有具体形体，仅用黑色漩涡与白色高光暗示存在。声波用同心圆白线向祁思远扩散，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'effect'),
    ('S4P2', f"【近景，画胸部以上半身，不出现全身】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。祁思远背贴墙壁，大口喘气，衬衫湿透贴在身上，眼神慌乱地望向虚空，一只手撑住桥壁，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'character'),
    ('S4P3', f"【中景，画腰部以上，人物占画面主体】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。从上方俯视祁思远，他渺小地蜷缩在桥洞中央，周围发光刻痕环绕如牢笼。黑白对比强烈，人物被阴影切割，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'scene'),
    ('S4P4', f"【近景，画胸部以上半身，不出现全身】黑暗中出现一双狭长眼睛或裂缝，带戏谑笑意，周围刻痕搏动更剧烈。眼睛用高光与黑色网点表现非人感，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'effect'),
    ('S4P5', f"【极端特写镜头，只画局部细节填满画面，不出现全身】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。祁思远眼神震动，嘴唇颤抖，眼泪在眼眶打转，厌倦被一语刺穿。画面用速度线聚焦瞳孔，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'character'),
    ('S4P6', f"【中景，画腰部以上，人物占画面主体】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。黑暗中伸出无形的阴影触须或巨大手掌轮廓，笼罩祁思远全身，压迫感极强。人物被阴影挤压在桥壁与黑暗之间，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'effect'),
    ('S4P7', f"【近景，画胸部以上半身，不出现全身】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。祁思远左手皮肤开始变灰黑，坏死线沿血管向上攀爬，手掌干瘪如焦木，血管凸显成黑色。黑白漫画中用强对比表现坏死，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'effect'),
    ('S5P1', f"【极端特写镜头，只画局部细节填满画面，不出现全身】灰黑色坏死线已爬到手腕上方，血管干枯龟裂，皮肤像烧焦树皮。坏死与正常肤色形成锐利分界线，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'effect'),
    ('S5P2', f"【近景，画胸部以上半身，不出现全身】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。祁思远仰头惨叫，面部极度扭曲，眼泪鼻涕横流，左手高举，坏死线逼近肘部。背景桥洞刻痕发出刺目光芒，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'character'),
    ('S5P3', f"【极端特写镜头，只画局部细节填满画面，不出现全身】黑色坏死如潮水退去，皮肤恢复血色，手指微微颤抖，指甲恢复粉红。黑白画面用细腻网点与高光表现复苏，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'effect'),
    ('S5P4', f"【中景，画腰部以上，人物占画面主体】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。祁思远踉跄冲出桥洞，夕阳已变深橙色，荒草丛中身影摇晃，一只手捂着胸口。桥洞黑影在身后如巨口，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'character'),
    ('S5P5', f"【全景远景，人物占画面1/3，环境为主】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。待拆街道，一盏未亮的路灯下，祁思远跪倒在地，双手撑地，喘息剧烈。远处是废墟与昏暗天际，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'scene'),
    ('S5P6', f"【极端特写镜头，只画局部细节填满画面，不出现全身】25岁东亚青年，细金属框眼镜，黑色短发齐刘海，米色休闲西装，深蓝色V领衬衫，旧黑色双肩背包，疲惫空洞的眼神，黑眼圈，苍白皮肤。祁思远低头看左手，手掌干干净净，但在黑白画面中用极淡的网点与一道几乎看不见的痕迹暗示某种烙印残留，East Asian B/W manhua, G-pen ink, high-contrast grayscale, 2D comic, NOT photo, NOT photorealistic, NOT realistic face.", 'character'),
]

BUBBLES = {
    'S1P1': [('narration', '每天早上七点五十分，他准时挤上开往市中心的地铁。', 'bottom')],
    'S1P2': [('narration', '他只是需要那个重量，那个能让他看起来有事可做的道具。', 'bottom')],
    'S1P3': [('narration', '保安换过两茬，没人问过他。', 'bottom')],
    'S1P4': [('narration', '中午，他去便利店买两个饭团。', 'bottom')],
    'S1P5': [('narration', '下午，他继续投那些永远不会有回音的简历。', 'bottom')],
    'S1P6': [('narration', '他知道自己在腐烂，只是腐烂得很安静。', 'bottom')],
    'S2P1': [('narration', '那天傍晚，他厌倦了。', 'bottom')],
    'S2P2': [('narration', '公园的入口藏在两堵危墙之间。', 'bottom')],
    'S2P3': [('narration', '公园早已荒废。', 'bottom')],
    'S2P4': [('narration', '最深处，是一座石桥。', 'bottom')],
    'S2P5': [('narration', '祁思远看见一个女人走进了那个阴影里。', 'bottom')],
    'S3P1': [('narration', '桥洞里比外面暗得多。', 'bottom')],
    'S3P2': [('narration', '那些刻痕覆盖了整个桥洞的内壁。', 'bottom')],
    'S3P3': [('narration', '它们在一明一暗地搏动，像心跳。', 'bottom')],
    'S3P4': [('narration', '他想跑，但双腿没有回应。', 'bottom')],
    'S3P5': [('narration', '“你在找什么？”', 'bottom')],
    'S4P1': [('narration', '“这里是世界的夹缝。”', 'bottom')],
    'S4P2': [('narration', '“你……你是谁？这是什么东西？”', 'bottom')],
    'S4P3': [('narration', '“你可以叫我……租客。”', 'bottom')],
    'S4P4': [('narration', '“你走进来的时候，眼睛里写满了厌倦。”', 'bottom')],
    'S4P5': [('narration', '“容器。”', 'bottom')],
    'S4P6': [('narration', '“我能给你一个机会。”', 'bottom')],
    'S4P7': [('narration', '“杀人。”', 'bottom')],
    'S5P1': [('narration', '“现在只是手臂。”', 'bottom')],
    'S5P2': [('narration', '“我答应！我答应你！”', 'bottom')],
    'S5P3': [('narration', '黑色的线停在手肘处，然后退去了。', 'bottom')],
    'S5P4': [('narration', '“我给你四小时。”', 'bottom')],
    'S5P5': [('narration', '他跑回那条待拆的街道，一直跑到双腿发软。', 'bottom')],
    'S5P6': [('narration', '他知道，有什么东西已经不一样了。', 'bottom')],
}