#!/usr/bin/env python3
"""第八章 佘山之门 — 穿越（38格）"""
Q="Young Chinese man 25yo, thin black-frame glasses, short black hair with bangs, beige casual blazer, dark blue V-neck shirt, tired hollow eyes, pale skin"
G="High school girl with ponytail, school uniform,棒棒糖, tired knowing eyes, young face"
S="Manhua ink wash, black white, dramatic lighting, G-pen linework, grayscale, realistic."
PANELS=[
("P38_扉页",f"Split: {Q} climbing stone steps up佘山 at night under moonlight, {G} figure waiting at peak, portal between times. {S}","abstract"),
("P01_辞职",f"Medium shot supervisor周姐 at desk clicking approve on OA system, looking up at {Q} with knowing professional restraint,不问不挽留. {S}","scene"),
("P02_离职证明",f"Close-up周姐 hands folding离职证明 along crease, sliding paper across desk, asking found new job yet, {Q}不敢看 her eyes. {S}","character"),
("P03_林小燕",f"Young female coworker peeking over cubicle partition, expression complex, intuitive person sensing wrongness without vocabulary, asking will you come back. {S}","character"),
("P04_看情况吧",f"Close-up {Q} face, words模糊弧度, not yes not no, walking away through gray fluorescent office lights, disappearing around corner. {S}","character"),
("P05_剪断命运线",f"Abstract: {Q} silhouette cutting threads connecting him to normal life, same gesture as cutting命运线, but this time他自己 being cut. {S}","abstract"),
("P06_打包人生",f"{Q} in small apartment packing twenty-five years into single backpack,退租,押金不要,银行卡余额取一半现金, other half to mother. {S}","character"),
("P07_扔手机",f"{Q} standing by苏州河, throwing phone and laptop into water, SIM card snapped, identity dissolving with每个动作, weight lifting. {S}","scene"),
("P08_苏州河边",f"Wide shot {Q} walking along苏州河, November Shanghai, plane tree leaves falling,下班 crowds rushing home, each person with destiny threads he can now see. {S}","scene"),
("P09_命运线可视",f"Close-up {Q} eyes seeing pedestrian命运 threads: some粗壮如缆绳, some细如蛛丝, some末端暗淡即将燃尽, visual回路 activated. {S}","abstract"),
("P10_已死之人",f"Medium shot {Q} at riverbank, feeling like dead man watching living world, or previously alive man watching those who still think they are alive. {S}","character"),
("P11_佘山脚下",f"Wide shot taxi dropping {Q} at佘山 base past midnight,尾灯 disappearing down mountain road, alone before dark forest. {S}","scene"),
("P12_深夜山林",f"Wide shot {Q} climbing stone steps through深夜山林, pine needles摩擦 in wind, dead branches falling, moonlight银绿 on moss, special stillness. {S}","scene"),
("P13_睁开命运之眼",f"Close-up {Q} eyes opening视觉回路, learned control over past week, self-taught like breathing, world peeling back layer. {S}","character"),
("P14_树的命图",f"Wide shot forest transformed through视觉回路: trees with faint命图 outlines like光晕, moonlight弯曲 by高维结构,凹陷 above山顶. {S}","abstract"),
("P15_陈姝没骗他",f"{Q} looking up at山顶凹陷 in space, this area确实不同,陈姝 told truth, portal exists. {S}","character"),
("P16_山顶路上",f"{Q} climbing, each step closer to凹陷, heart beating faster than climbing warrants, remembering桥洞,房东溃烂 face, 230 faces. {S}","character"),
("P17_哪些是误判",f"Close-up {Q} face at半山腰 platform, palms sweating, dark thought surfacing: which of 230 were guilty, which were误判, which did房东刻意引导 him to kill. {S}","character"),
("P18_浮起的尸体",f"Abstract: dead question rising from deep water like corpse,完整展现在面前, {Q} frozen,山下已经没有他的位置了. {S}","abstract"),
("P19_抵达山顶",f"Wide shot {Q} reaching佘山 highest point, giant rock larger than childhood memory, surface covered with glowing刻痕 identical to bridge cave. {S}","scene"),
("P20_发光刻痕",f"Close-up rock surface刻痕 pulsing slowly like deep sea creature breathing, not文字 not符号,介于几何与脉搏之间的结构. {S}","supernatural"),
("P21_陈姝已到",f"Wide shot {G} sitting on rock with back to {Q}, one leg dangling,校服裙摆 swaying in night breeze, moonlight silver outline, unwrapping棒棒糖. {S}","character"),
("P22_你很准时",f"Close-up {G} not turning around, acknowledging arrival,糖纸搓成小球弹进草丛, casual穿越 veteran demeanor. {S}","character"),
("P23_门半开着",f"Medium shot {Q} standing five meters away, asking about门, {G} saying half-open, like unlatched window, just need correct angle to push through. {S}","character"),
("P24_电子设备全处理",f"Close-up {G} face, confirming preparations complete: electronics destroyed, only cash kept, identity abandoned, everything weighing为零. {S}","character"),
("P25_没有了",f"Close-up {Q} face, three seconds of silence, mind flashing周姐纸,林小燕 face, mother voice, but lips say three words:没有了. {S}","character"),
("P26_你是第一个",f"Medium shot {G} admitting {Q} is first person she has brought across, silence two seconds, wind suddenly stronger from east with wrong-season cold. {S}","character"),
("P27_伸出手腕",f"Close-up {G} extending hand, telling {Q} hold wrist, do not let go no matter what happens, her手腕 thin but vibrating with strange internal frequency. {S}","character"),
("P28_七道蓝线",f"Wide shot: {G} other hand drawing precise轨迹 in air, seven blue lines appearing like蛛丝, forming irregular geometric pattern. {S}","supernatural"),
("P29_掌心一翻",f"Close-up {G} palm flipping, seven lines simultaneously snapping, world beginning to change. {S}","supernatural"),
("P30_世界塌缩",f"Abstract: city lights flattening from distance inward, three-dimensional space pressed into thicknessless photograph, sky folding, mountain folding, self folding. {S}","abstract"),
("P31_光的薄片",f"Abstract: everything becoming light sheets layered like infinite book pages, each page a complete moment: bridge雨夜, elevator红光,凉透羊肉串,陈姝 face dissolving. {S}","abstract"),
("P32_撕裂",f"Abstract: world surface tearing from single point expanding from针孔 to漩涡 to无边开口, colors beyond visible spectrum, question without question mark. {S}","abstract"),
("P33_无限细的线",f"Abstract: {Q} consciousness stretched into infinitely thin line through infinitely narrow hole, sliding through all time fragments,宇宙操作系统的底层漏洞. {S}","abstract"),
("P34_死了三次",f"Abstract: three death experiences, each真实不容置疑, heartbeat stopping, consciousness dissolving, self边界瓦解, each time remembering陈姝 words:不要信. {S}","abstract"),
("P35_第四次的臣服",f"Abstract: {Q} no longer struggling, surrender, letting go, acceptance of dissolution, then everything returning. {S}","abstract"),
("P36_陌生的地面",f"Wide shot: {Q} on knees on smooth slightly elastic ground material, cold temperature, lungs contracting on wrong air, coughing like第一次学会呼吸. {S}","scene"),
("P37_蜜色的天空",f"Wide shot {Q} looking up: narrow巷道 between gray-white walls with faint fluorescence, strip of sky above showing honey-colored uniform glow, no sun no clouds no gradient, entire sky one giant default background screen. {S}","scene"),
]
